language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSWER_INSTALL="composer require symfony/process:3.2.* symfony/console:3.2.*"
    - COMPOSWER_INSTALL="composer require symfony/process:3.4.* symfony/console:3.4.*"
    - COMPOSWER_INSTALL="composer require symfony/process:4.2.* symfony/console:4.2.*"

install: $COMPOSWER_INSTALL

script: vendor/bin/grumphp run && composer test

after_success: bash <(curl -s https://codecov.io/bash)
