language: php

php:
  - "7.3"
  - "7.4"
  - "nightly"

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - SYMFONY_VERSION="4.4.*"
    - SYMFONY_VERSION="5.0.*"

matrix:
  allow_failures:
    - php: nightly

install: composer require symfony/process:$SYMFONY_VERSION symfony/console:$SYMFONY_VERSION

script:
  - vendor/bin/grumphp run
  - composer test
  - composer infection
  - composer phpstan

after_success: bash <(curl -s https://codecov.io/bash)
