language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - SYMFOMY_UPDATE="composer update symfony/* --prefer-lowest && "
    - SYMFONY_UPDATE=""

install: composer install --no-suggest

script: $SYMFONY_UPDATE vendor/bin/grumphp run && composer test

after_success: bash <(curl -s https://codecov.io/bash)
