version: '2'

services:
  host_a:
    build: .
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
    ports:
      - "2208:22"
  host_b:
    build: .
    volumes:
      - "./authorized_keys:/home/user/.ssh/authorized_keys"
